# **🌍 Predicción de Calidad del Aire Urbano**

## **Semana1**

### ***Importaciones***

In [19]:
import os
import requests
import pandas as pd

API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmb2RheGltMzkzQG5hemlzYXQuY29tIiwianRpIjoiMzQxZDM5YjYtOTgyMS00ZjMyLTg0ZDgtYzExZTAzYjcyYWFmIiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE3NzU1NTg5NjIsInVzZXJJZCI6IjM0MWQzOWI2LTk4MjEtNGYzMi04NGQ4LWMxMWUwM2I3MmFhZiIsInJvbGUiOiIifQ.NSsTFowKQPs6TpKFjAgfLT8r6hZQiVGOLrmBzFszl5M"

### ***API***

In [20]:
def get_aemet_observaciones():
    url = "https://opendata.aemet.es/opendata/api/observacion/convencional/todas"
    headers = {"api_key": API_KEY}

    r1 = requests.get(url, headers=headers, timeout=30)
    r1.raise_for_status()
    meta = r1.json()

    r2 = requests.get(meta["datos"], timeout=30)
    r2.raise_for_status()
    return r2.json()

data = get_aemet_observaciones()

df = pd.DataFrame(data)

columnas_interes = [c for c in [
    "idema", "ubi", "fint", "ta", "hr", "pres", "vv", "dv", "lat", "lon", "alt"
] if c in df.columns]

df = df[columnas_interes]
print(df.head(50))

    idema                                ubi                      fint    ta  \
0   0009X                            ALFORJA  2026-04-08T03:00:00+0000   9.0
1   0016A                   REUS  AEROPUERTO  2026-04-08T03:00:00+0000   NaN
2   0034X                              VALLS  2026-04-08T03:00:00+0000   8.1
3   0042Y          TARRAGONA  FAC. GEOGRAFIA  2026-04-08T03:00:00+0000   9.8
4   0061X                            PONTONS  2026-04-08T03:00:00+0000   7.3
5   0066X             VILAFRANCA DEL PENEDÈS  2026-04-08T03:00:00+0000   8.3
6   0073X                  SITGES  VALLCARCA  2026-04-08T03:00:00+0000  10.0
7    0076              BARCELONA  AEROPUERTO  2026-04-08T03:00:00+0000  11.8
8   0092X                   BERGA  INSTITUTO  2026-04-08T03:00:00+0000  10.0
9   0106X                          BALSARENY  2026-04-08T03:00:00+0000   3.9
10  0114X                  PRATS DE LLUÇANÈS  2026-04-08T03:00:00+0000   4.8
11  0120X                               MOIÀ  2026-04-08T03:00:00+0000  12.3
12  0149X                            MANRESA  2026-04-08T03:00:00+0000   6.9
13  0158X                         MONTSERRAT  2026-04-08T03:00:00+0000  14.3
14  0171X                           IGUALADA  2026-04-08T03:00:00+0000   7.6
15  0194D            CORBERA  PUIG D?AGULLES  2026-04-08T03:00:00+0000  14.1
16  0201D            BARCELONA  PORT OLÍMPIC  2026-04-08T03:00:00+0000  13.7
17  0201X               BARCELONA  DRASSANES  2026-04-08T03:00:00+0000  13.9
18  0222X                  CALDES DE MONTBUI  2026-04-08T03:00:00+0000   NaN
19  0244X                   VILASSAR DE DALT  2026-04-08T03:00:00+0000  11.3
20  0260X                        FONTMARTINA  2026-04-08T03:00:00+0000  12.3
21  0281Y            BLANES  JARDIN BOTANICO  2026-04-08T03:00:00+0000  12.2
22  0312X               SANT PAU DE SEGURIES  2026-04-08T03:00:00+0000   2.3
23  0320I                           PLANOLES  2026-04-08T03:00:00+0000   8.3
24  0360X              LES PLANES D?HOSTOLES  2026-04-08T03:00:00+0000   3.6
25  0363X                        SANT HILARI  2026-04-08T03:00:00+0000   7.9
26   0367                 GIRONA  AEROPUERTO  2026-04-08T03:00:00+0000   6.3
27  0370E            GIRONA  PARC DEL MIGDIA  2026-04-08T03:00:00+0000   9.5
28  0372C                          PORQUERES  2026-04-08T03:00:00+0000   7.5
29  0385X                         L?ESTARTIT  2026-04-08T03:00:00+0000  13.1
30  0394X                     VALL DE BIANYA  2026-04-08T03:00:00+0000   5.3
31  0411X                CASTELLO D?EMPURIES  2026-04-08T03:00:00+0000   8.8
32  0413A                MAÇANET DE CABRENYS  2026-04-08T03:00:00+0000   7.2
33  0421X               ESPOLLA  LES ALBERES  2026-04-08T03:00:00+0000   8.1
34  0429X               FIGUERES  ELS ASPRES  2026-04-08T03:00:00+0000  10.0
35  1002Y                    BAZTÁN  IRURITA  2026-04-08T03:00:00+0000   8.6
36  1010X                               BERA  2026-04-08T03:00:00+0000  10.7
37  1012P                               IRUN  2026-04-08T03:00:00+0000  19.5
38  1014A  DONOSTIA/SAN SEBASTIÁN AEROPUERTO  2026-04-08T03:00:00+0000  14.7
39  1021X                 ERRENTERIA  AÑARBE  2026-04-08T03:00:00+0000  21.9
40  1025A                             SEGURA  2026-04-08T03:00:00+0000  16.9
41  1025X                  BEASAIN  ARRIARAN  2026-04-08T03:00:00+0000  16.2
42  1026X                            ORDIZIA  2026-04-08T03:00:00+0000  18.6
43  1033X                             ARESO   2026-04-08T03:00:00+0000  18.5
44  1037X                            LEGAZPI  2026-04-08T03:00:00+0000  18.5
45  1037Y                          ZUMARRAGA  2026-04-08T03:00:00+0000  18.0
46  1038X                           AZPEITIA  2026-04-08T03:00:00+0000  13.3
47  1041A                             ZUMAIA  2026-04-08T03:00:00+0000  14.6
48  1044X                  ARAMAIO  ETXAGUEN  2026-04-08T03:00:00+0000  16.9
49  1048X                       ARETXABALETA  2026-04-08T03:00:00+0000  20.2

       hr    pres   vv     dv        lat       lon     alt
0    57.0     NaN  1.3  276.0  41.213892  0.963335   406.0
1     NaN  1009.9  2.9   20.0  41.145000  1.163611    71.0
2    67.0     NaN  NaN    NaN  41.293053  1.260838   233.0
3    75.0     NaN  0.6   87.0  41.123892  1.249167    55.0
4    42.0     NaN  2.3  313.0  41.417052  1.519269   632.0
5    81.0     NaN  0.1   99.0  41.330279  1.676942   177.0
6    74.0     NaN  0.6  333.0  41.243784  1.852626    58.0
7    71.0  1018.7  4.3   10.0  41.292781  2.069995     4.0
8    53.0     NaN  2.5   71.0  42.101388  1.857494   682.0
9    88.0     NaN  0.7  302.0  41.866387  1.872504   361.0
10   86.0     NaN  1.1  342.0  42.007057  2.026561   700.0
11   40.0     NaN  0.3   10.0  41.813278  2.095390   742.0
12   79.0   986.3  1.2   24.0  41.719881  1.840280   291.0
13   34.0     NaN  NaN    NaN  41.594444  1.839223   738.0
14   57.0     NaN  0.7  271.0  41.578889  1.617778   313.0
15   32.0     NaN  NaN    NaN  41.408192  1.885000   647.0
16   79.0     NaN  2.8  357.0  41.390555  2.200001    26.0
17   73.0     NaN  0.0  263.0  41.374998  2.173886    11.0
18    NaN     NaN  2.2  299.0  41.612663  2.168412   175.0
19   79.0     NaN  0.8  322.0  41.504893  2.362637    56.0
20   38.0     NaN  NaN    NaN  41.760064  2.431023   936.0
21   83.0     NaN  0.9   23.0  41.677054  2.805112    45.0
22   92.0     NaN  0.1  193.0  42.258444  2.364353   851.0
23   50.0     NaN  0.4   11.0  42.316878  2.102774  1151.0
24   97.0     NaN  0.5  346.0  42.052837  2.551007   337.0
25   58.0     NaN  0.5  233.0  41.880833  2.513329   810.0
26  100.0  1003.9  0.0    0.0  41.911665  2.763329   143.0
27   94.0     NaN  0.6  282.0  41.972333  2.819442    76.0
28   93.0     NaN  0.5  283.0  42.104444  2.763611   157.0
29   94.0     NaN  1.3  248.0  42.053888  3.201389     1.0
30   93.0     NaN  0.3  253.0  42.210555  2.471827   350.0
31  100.0     NaN  1.3  258.0  42.224834  3.093053     2.0
32   94.0     NaN  0.8  293.0  42.386925  2.755580   355.0
33   89.0     NaN  0.8   24.0  42.389881  3.006114   100.0
34   89.0     NaN  0.1  295.0  42.259082  2.960328    45.0
35   94.0     NaN  0.4  133.0  43.135722 -1.542961   183.0
36   85.0     NaN  0.2  145.0  43.278691 -1.675786    54.0
37   40.0     NaN  0.3  240.0  43.326407 -1.796536   120.0
38   69.0  1016.0  1.6  200.0  43.357075 -1.792116     4.0
39   32.0     NaN  3.9  165.0  43.213834 -1.878823   165.0
40   46.0     NaN  0.4  276.0  43.015553 -2.256663   255.0
41   47.0     NaN  0.6   14.0  43.054634 -2.232037   255.0
42   41.0     NaN  3.0  276.0  43.058158 -2.184273   290.0
43   34.0     NaN  4.4  195.0  43.084999 -1.950836   520.0
44   36.0     NaN  NaN    NaN  43.051797 -2.337095   460.0
45   35.0   967.3  0.9  287.0  43.079917 -2.317500   420.0
46   67.0     NaN  0.6   98.0  43.172576 -2.267175   180.0
47   67.0  1013.5  3.5  119.0  43.302139 -2.251035    28.0
48   39.0     NaN  NaN    NaN  43.057835 -2.589645   617.0
49   32.0     NaN  NaN    NaN  43.025050 -2.465715   308.0

### ***Columnas***

In [21]:
rename_columns = {
    "idema": "station_id",
    "ubi": "station_name",
    "fint": "datetime",
    "ta": "temperature",
    "hr": "humidity",
    "pres": "pressure",
    "vv": "wind_speed",
    "dv": "wind_direction",
    "lat": "latitude",
    "lon": "longitude",
    "alt": "altitude"
}

In [22]:
df = df.rename(columns=rename_columns)

df.head()

,station_id,station_name,datetime,temperature,humidity,pressure,wind_speed,wind_direction,latitude,longitude,altitude
0,0009X,ALFORJA,2026-04-08T03:00:00+0000,9.0,57.0,NaN,1.3,276.0,41.213892,0.963335,406.0
1,0016A,REUS AEROPUERTO,2026-04-08T03:00:00+0000,NaN,NaN,1009.9,2.9,20.0,41.145000,1.163611,71.0
2,0034X,VALLS,2026-04-08T03:00:00+0000,8.1,67.0,NaN,NaN,NaN,41.293053,1.260838,233.0
3,0042Y,TARRAGONA FAC. GEOGRAFIA,2026-04-08T03:00:00+0000,9.8,75.0,NaN,0.6,87.0,41.123892,1.249167,55.0
4,0061X,PONTONS,2026-04-08T03:00:00+0000,7.3,42.0,NaN,2.3,313.0,41.417052,1.519269,632.0

In [23]:
df["datetime"] = pd.to_datetime(df["datetime"])

cols = ["temperature", "humidity", "pressure", "wind_speed"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# quitar filas sin fecha
df = df.dropna(subset=["datetime"])

# ordenar
df = df.sort_values("datetime")

In [24]:
# Utilizaremos Madrid
df = df[df["station_name"].str.contains("MADRID", case=False, na=False)]

df.to_csv("../data/processed/weather.csv", index=False)

### ***Dataset calidad del aire***

In [25]:
air = pd.read_csv("../data/raw/air_quality_madrid.csv", sep=";")

air.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,28,79,11,12,28079011_12_8,2025,1,1,30.0,V,...,75.0,V,249.0,V,306.0,V,219.0,V,191.0,V
1,28,79,11,12,28079011_12_8,2025,1,2,150.0,V,...,49.0,V,41.0,V,56.0,V,38.0,V,25.0,V
2,28,79,11,12,28079011_12_8,2025,1,3,17.0,V,...,175.0,V,212.0,V,152.0,V,63.0,V,99.0,V
3,28,79,11,12,28079011_12_8,2025,1,4,173.0,V,...,61.0,V,69.0,V,76.0,V,68.0,V,56.0,V
4,28,79,11,12,28079011_12_8,2025,1,5,68.0,V,...,40.0,V,33.0,V,32.0,V,30.0,V,22.0,V

In [26]:
air.columns

Index(['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO',
       'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04',
       'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09',
       'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14',
       'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19',
       'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24',
       'V24'],
      dtype='object')

In [27]:
air = air[air["MAGNITUD"] == 12] # Filtramos por NO2, la magnitud indica el contaminante, 12 es NO2

air = air[air["ESTACION"] == 11]  # Elejimos la estación, ejemplo Ramón y Cajal

# Metemos la fecha, que esta dividida en varias columnas, en una sola en formato datatime
air["date"] = pd.to_datetime(
    air["ANO"].astype(str) + "-" +
    air["MES"].astype(str) + "-" +
    air["DIA"].astype(str)
)

In [28]:
# Transformamos a formato LONG (clave)
rows = []

for _, row in air.iterrows():
    for h in range(1, 25):
        value = row[f"H{h:02d}"]
        
        # saltar valores nulos
        if pd.isna(value):
            continue
        
        datetime = row["date"] + pd.Timedelta(hours=h-1)
        
        rows.append({
            "datetime": datetime,
            "no2": value
        })

df_air = pd.DataFrame(rows)

In [29]:
# Limpiamos el dataset
df_air["no2"] = pd.to_numeric(df_air["no2"], errors="coerce")
df_air = df_air.dropna()
df_air = df_air.sort_values("datetime")

In [30]:
# Guardamos el dataset
df_air.to_csv("../data/processed/air_quality_clean.csv", index=False)

In [31]:
rows = []

for _, row in air.iterrows():
    for h in range(1, 25):

        # comprobar si el dato es válido
        if row[f"V{h:02d}"] != "V":
            continue

        value = row[f"H{h:02d}"]

        if pd.isna(value):
            continue

        datetime = row["date"] + pd.Timedelta(hours=h-1)

        rows.append({
            "datetime": datetime,
            "no2": value
        })

df_air.head()

             datetime   no2
0 2025-01-01 00:00:00  30.0
1 2025-01-01 01:00:00  46.0
2 2025-01-01 02:00:00  65.0
3 2025-01-01 03:00:00  60.0
4 2025-01-01 04:00:00  44.0

### ***Concatenación entre ambos datasets***

In [ ]:
weather = pd.read_csv("../data/processed/weather.csv")
weather["datetime"] = pd.to_datetime(weather["datetime"])

weather.head()

,station_id,station_name,datetime,temperature,humidity,pressure,wind_speed,wind_direction,latitude,longitude,altitude
0,9501X,VALMADRID,2026-04-08 03:00:00+00:00,10.2,55.0,NaN,1.4,189.0,41.443134,-0.885947,535.0
1,4067,MADRIDEJOS,2026-04-08 03:00:00+00:00,12.4,79.0,938.1,1.2,236.0,39.492064,-3.528358,690.0
2,3129,MADRID/BARAJAS,2026-04-08 03:00:00+00:00,12.3,84.0,950.9,3.0,270.0,40.466559,-3.555593,609.0
3,3129A,MADRID BARAJAS RS.,2026-04-08 03:00:00+00:00,11.5,92.0,945.2,2.1,287.0,40.465278,-3.579722,631.0
4,3194U,MADRID C. UNIVERSITARIA,2026-04-08 03:00:00+00:00,11.4,99.0,NaN,1.3,353.0,40.451671,-3.724167,664.0

In [41]:
air = pd.read_csv("../data/processed/air_quality_clean.csv")
air["datetime"] = pd.to_datetime(air["datetime"])

air.head()

             datetime   no2
0 2025-01-01 00:00:00  30.0
1 2025-01-01 01:00:00  46.0
2 2025-01-01 02:00:00  65.0
3 2025-01-01 03:00:00  60.0
4 2025-01-01 04:00:00  44.0